# Generated by Django 4.2.10 on 2024-03-01 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=10)),
                ('apodo', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('fecha', models.DateTimeField()),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to='imagenes/')),
                ('cuerpo', models.CharField(max_length=5000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.CharField(max_length=120)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.usuarios')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.post')),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to='avatares/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
